---
abstract: 'MetaTrans plugin for wordbook.cz.'
author:
  - 'Jan Pomikalek <xpomikal@fi.muni.cz>'
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl-5
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MetaTrans-WordBook
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Entities: 0
  HTTP::Request: 0
  HTTP::Response: 0
  LWP::UserAgent: 0
  MetaTrans: 1.06
  Proc::SyncExec: 0
  Readonly: 0
  URI::Escape: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=MetaTrans
  homepage: https://github.com/tupinek/MetaTrans
  repository: git://github.com/tupinek/MetaTrans
version: 1.06
