---
abstract: 'MetaTrans plugin for wordbook.cz.'
author:
  - 'Jan Pomikalek <xpomikal@fi.muni.cz>'
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl-5
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MetaTrans-WordBookCz
no_index:
  directory:
    - inc
    - t
requires:
  HTTP::Request: 0
  MetaTrans: 1.06
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=MetaTrans-WordbookCz
  homepage: https://github.com/tupinek/MetaTrans-WordbookCz
  repository: git://github.com/tupinek/MetaTrans-WordbookCz
version: 1.06
